### ISSUE TITLE
npm install on windows requires C:\OpenSSL-Win64

### ISSUE THREAD

**Issue by bridiver** [brave/ledger-client#19]
Running npm install on browser-laptop windows will produce an error that npm install tries very hard to hide from you
```
LINK : fatal error LNK1181: cannot open input file 'C:\OpenSSL-Win64\lib\libeay32.lib' [C:\Users\vagrant\browser-laptop
-bootstrap\src\browser-laptop\node_modules\secp256k1\build\secp256k1.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\vagrant\browser-laptop-bootstrap\src\browser-laptop\node_modules\secp256k1
gyp ERR! node -v v7.2.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "rebuild"
npm ERR! node v7.2.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! secp256k1@3.0.1 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
```

unfortunately after that error it proceeds to do a bunch of other stuff that makes it look like everything ran fine unless you notice `npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1` which you might interpret to be a non-error for the optional dependency. `secp256k1` is added by a bitcoin library and we need to do something to remove the openssl dependency. I have no idea why it exists in the first place because node has openssl built-in.

**Comment by bridiver** [comment]
and just to make things even more fun it is looking for a lib that doesn't even exist in the latest versions at https://slproweb.com/products/Win32OpenSSL.html

**Comment by bridiver** [comment]
it appears to be an optional dependency so maybe we can opt out

**Comment by mrose17** [comment]
@bsclifton - may i impose on you to take a look at this and determine the "simplest" fix??? thanks!

**Comment by bridiver** [comment]
the simplest fix might be generating a prebuilt binary. I also opened a ticket https://github.com/cryptocoinjs/secp256k1-node/issues/108

**Comment by bsclifton** [comment]
I updated documentation in the wiki (calling out using the older version) for the time being, until we can work this out :smile:

**Comment by mrose17** [comment]
@bsclifton - anything to be done now or are we still in a holding pattern?

**Comment by bsclifton** [comment]
@mrose17 no updated as far as I know

**Comment by mrose17** [comment]
OBE
