### ISSUE TITLE
Remove cmake dep or npm install by just having node-gyp

### ISSUE THREAD

**Issue by bbondy** [brave/ledger-client#7]
ledger-client and hence node-anonize2-relic fails to npm install when cmake is not installed.
Our dependencies are already pretty hard for browser-laptop so it would be ideal if we didn't have to have this.

I see a couple of possible routes:

i) Make this npm install via compiling with node-gyp ?
https://github.com/bbondy/abp-filter-parser-cpp/blob/master/binding.gyp

ii) Have a ledger-client not have this as a dependency at all and have pre-compiled .node files (would need to be updated on each node upgrade).  One example of this is electron-prebuilt which pulls down a pre-built binary instead of building a new one.

In the end I need to be able to do:

`npm install --save ledger-client` then require it and use it.

**Comment by mrose17** [comment]
OBE (overtaken by events): the package now uses the https://github.com/brave/node-anonize2-relic-emscripten package!
