### ISSUE TITLE
CLI script for triggering reconciliation using State and Publisher synopsis data from Brave?

### ISSUE THREAD

**Issue by willy-b** [brave/ledger-client#9]
@mrose17, @diracdeltas,

To test how `ledger-client` updates affect things in`browser-laptop` one often needs to regenerate their `ledger-state` (`~/.config/brave/ledger-state.json`).

One can wipe out `ledger-*.json`, start Brave, and browse pages, but a reconciliation must be triggered to see `transactions` structure changes, e.g. like those that were introduced by  @mrose17's hot patch in https://github.com/brave/browser-laptop/commit/55c0e10ca3884b02a2e94d9250a5d8791f27a502#commitcomment-18801883 .

**Do you know an easy way to trigger reconciliation from the commandline, while incorporating `ledger-synopsis.json` data?**

So far I just update the `reconcileStamp` in  `ledger-state.json` to be close to present and wait, but there is a long random delay before Brave will fire it off.

I was inspired by the `blastoff.js` script here in `ledger-client` to see if there was a CLI solution to triggering reconciliation while including a browsing synopsis generated by Brave (e.g. from `~/.config/brave/ledger-synopsis.json`). Do you know of one?

I tried a few things:
 `ledger-state.json` CAN be passed into `blastoff.js`,  to trigger a reconciliation **but it won't include any of the browsing synopsis information**, so there are no `ballots` or `votes` on the returned transaction object.

EXAMPLE:
I captured the value of the `state` variable passed at runtime to `ledger-client` by Brave (which is different than the `~/.config/brave/ledger-state.json` for some reason!) and saved it to a `config.json` file.
Then I updated the `reconcileStamp` to 3 min into future, and passed it to `blastoff.js` (following the example from `package.json`):

```
DEBUG=*,-babel ./blastoff.js -d -l -v -s https://ledger.brave.com/ -f ./config.json
```

This triggers reconciliation, and updates the same `./config.json` file with a transaction -- which lacks `ballots` or `votes` fields:

```
"transactions": [
    {
      "viewingId": "4545843b-6ced-4b67-8e91-300197f37826",
      "surveyorId": "BI+hjsm8sUKca7pPx9PABgS9eN2SgSi6AFUoK/UAFox",
      "contribution": {
        "fiat": {
          "amount": 5,
          "currency": "USD"
        },
        "rates": {
          "USD": 575.84
        },
        "satoshis": 858552,
        "fee": 9745
      },
      "submissionStamp": 1472336415266,
      "submissionDate": "2016-08-27T22:20:15.266Z",
      "submissionId": "f0b1870e942751fa68c0104ed628c5a387e244eddff72bc43680a4b690edb8c3"
    }
  ]
```

Also, do you  know why the `~/.config/brave/ledger-state.json` file has a different `personaId` and other data than the `state` object passed to `ledger-client` at runtime?

Thanks in advance

**Comment by willy-b** [comment]
If nothing exists already, I can probably add an argument to `blastoff.js` that specifies a `ledger-synopsis` file, then:
- read the `ledger-synopsis` JSON to get browsing data
- apply the votes to the `ledger-client` object  (using `client.vote`) before triggering the reconcile
- use the same logic as the `run` method in `browser-laptop/app/ledger.js` to determine the votes.

Just want to make sure I'm not missing some easy way the Brave team is already doing this.

**Comment by mrose17** [comment]
hi. just a quick note before i go _afk_ for a while. here is how i force a reconciliation:

1. quit browser
2. edit `ledger-state*.json` file to change `reconcileStamp` from `14...` to `13...`
3. start browser

this puts the reconciliation time into the past, so after the browser starts up and catches its breath, it will do a reconciliation.

however, there is one "gotcha" ... you are limited to at most reconciliation per day. if you need to do more than one per day (i do, from time to time), just ping me and i can create a new contribution surveyor, which "resets" the limit...

more details later!

best,

/mtr

**Comment by mrose17** [comment]
@willy-b - after we take care of the ledger statements, would you like to submit a PR for this? thanks!

**Comment by willy-b** [comment]
Sure!

**Comment by willy-b** [comment]
outdated, closing.
